export const DEFAULT_ROOM_MAX_PARTICIPANTS = 10;
export const POMODORO_DEFAULT_DURATION_SECONDS = 1500; // 25 minutes
export const REDIS_PROMPT_CACHE_TTL_SECONDS = 86400; // 24 hours
export const DAILY_AI_TOKEN_BUDGET_SOFT_CAP = 500000;
export const DAILY_AI_TOKEN_BUDGET_HARD_CAP = 1000000;
