import { Injectable, Logger } from '@nestjs/common';

@Injectable()
export class OpenAIProvider {
  private readonly logger = new Logger(OpenAIProvider.name);

  async generateCompletion(prompt: string) {
    const model = process.env.OPENAI_MODEL || 'gpt-4o';
    this.logger.log(`Executing OpenAI completion on model ${model}...`);
    return {
      text: `AI Study Note Summary generated by ${model}.\n- Key takeaway: Active recall improves retention.\n- Key takeaway: Group whiteboards accelerate problem solving.`,
      modelUsed: model,
    };
  }
}
